export default {
    'USER_ACCOUNT_STATUS_REQUEST': 'USER_ACCOUNT_STATUS_REQUEST',
    'USER_ACCOUNT_REQUEST_SUCCESS': 'USER_ACCOUNT_STATUS_REQUEST_SUCCESS',
    'USER_ACCOUNT_STATUS_REQUEST_FAILURE': 'USER_ACCOUNT_STATUS_REQUEST',
    'TRADES_REQUEST': 'TRADES_REQUEST',
    'TRADES_REQUEST_SUCCESS': 'TRADES_REQUEST_SUCCESS',
    'TRADES_REQUEST_FAILURE': 'TRADES_REQUEST_FAILURE',
    'TICKER_REQUEST': 'TICKER_REQUEST',
    'TICKER_REQUEST_SUCCESS': 'TICKER_REQUEST',
    'TICKER_REQUEST_FAILURE': 'TICKER_REQUEST_FAILURE'
}